export const ConfigurationServiceInjector = {
  KAKAO_SERVICE: "KAKAO_SERVICE",
  SWAGGER_SERVICE: "SWAGGER_SERVICE",
  TOKEN_SERVICE: "TOKEN_SERVICE",
  REDIS_SERVICE: "REDIS_SERVICE",
  MAIL_SERVICE: "MAIL_SERVICE",
} as const;
