version: "3.7"

services:
  # nestjs_server:
  #   container_name: server_api
  #   build:
  #     context: .
  #     dockerfile: dockerfile
  #     target: deps
  #   volumes:
  #     - .:/usr/src/306_poten_day/app
  #     - /usr/src/potenday/app/node_modules
  #   ports:
  #     - 3000:3000
  #   restart: always
  #   command: yarn start:dev
  #   networks:
  #     - test-networks

  postgres-container:
    container_name: 306_poten_day_db
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "wlals12!"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - test-networks

networks:
  test-networks:
    driver: bridge
