version: '3.7'

services:
  db-postgres:
    container_name: db-postgres
    image: postgres:15
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - network-backend
  
  redis:
    container_name: redis
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - network-backend

networks:
  network-backend:
    driver: bridge
    name: network-backend
