name: CI/CD

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUBID }}
          password: ${{ secrets.DOCKERHUBTOKEN }}

      - name: Get Env Access To Secrets
        run: |
          mkdir ./src/envs
          cd ./src/envs
          touch ./production.env
          echo "${{secrets.PRODUCTION_ENV}}" > ./production.env
        shell: bash

      # - name: pwd
      #   run: ls src/envs

      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_IMAGE }}

  # aws-deploy:
  #   runs-on: ubuntu-latest
  #   step:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ secrets.AWS_REGION }}

  ## deploy to production
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }} # EC2 퍼블릭 IPv4 DNS
          username: ${{ secrets.AWS_USERNAME }}
          port: 22
          key: ${{ secrets.AWS_KEY }}
          script: |
            docker ps
            docker pull ${{ secrets.DOCKER_IMAGE }}
            docker-compose -f docker-compose.prod.yml up -d --build
